version: "3.8"

services:
  github-runner:
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-runner:latest
    container_name: github-runner
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-work:/home/runner/_work

volumes:
  runner-work: